//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace service_station.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Car
    {
        [Required]
        public int IdCar { get; set; }
        [Required]
        public int IdClient { get; set; }
        [Required]
        public string VIN { get; set; }
        [Required]

        public string Make { get; set; }
        [Required]
        public string Model { get; set; }
        [Required]
        public string Year { get; set; }
    
        public virtual ClientCard ClientCard { get; set; }
        public virtual Order Order { get; set; }
    }
}
